// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akdziepbqtjokpvkytee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFrZHppZXBicXRqb2twdmt5dGVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTczNzMsImV4cCI6MjA2NTQ5MzM3M30.AD71-c-PPvu4cjTcCwLwDr62HsBfe38MByGv7-MIoIM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);